@startuml PAT-fine-v1
!$LIGHT = 1
!includeurl https://raw.githubusercontent.com/XaBerr/plantUMLstyle/master/style.plantuml

hide members

rectangle "position sensitive device" as sensor
rectangle "PID KPA101" as controller
rectangle "two axis motors" as actuator
rectangle "fast steering mirror" as system

circle "input\lvolt\lposition\l(x,y)" as x
circle "output\rvolt\rposition\r(x,y)" as y
circle "error\rdelta\rvolt" as e
circle "vibrations + beam fluctuation" as d

x -right--> e
e -right-> controller
controller -right-> actuator
actuator -right-> system
d -down-> system
system -right-> y
y -down-> sensor
sensor --> e

@enduml
