@startuml QKD
!$LIGHT = 1
!includeurl https://raw.githubusercontent.com/XaBerr/plantUMLstyle/master/style.plantuml

hide members

rectangle "Alice" as a
rectangle "Bob" as b

a <-right-> b : "PAT"
a <-right-> b : "Synchro"
a <-right-> b : "Telecom"


@enduml
