@startuml simplified-model
!$LIGHT = 1
!includeurl https://raw.githubusercontent.com/XaBerr/plantUMLstyle/master/style.plantuml

object sensor {
  camera
  psd
}

object controller {
  kpa101
  pc
}

object actuator {
  mirror
  skywatcher
}

sensor <-right-> controller
actuator <-left-> controller

@enduml