@startuml simplified-model
!$LIGHT = 1
!includeurl https://raw.githubusercontent.com/XaBerr/plantUMLstyle/master/style.plantuml

object sensor {
  camera
  psd
}

object controller {
  kpa101
  pc
}

object actuator {
  mirror
  skywatch
}

circle "input beam" as x
circle "output beam" as y

x -right-> actuator
actuator -right-> y
y -down-> sensor
sensor -left-> controller
controller -up-> actuator

@enduml